use_frameworks!

platform :ios, '10.0'

target 'SwiftUIValueSlider_Example' do
  pod 'SwiftUIValueSlider', :path => '../'

  target 'SwiftUIValueSlider_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
